---
title: "SS4850 Final Project"
author: "Rui Zhu"
date: "4/6/2021"
output:
  word_document: default
  pdf_document: default
---



# Explanatory analysis

```{r}
HCVdata <- read.csv(file = 'hcvdat0.csv')
suppressMessages(library(dplyr))
drop <- c("X")
HCVdata = HCVdata[,!(names(HCVdata) %in% drop)]
colnames(HCVdata) = c("Category","Age","Sex","ALB","ALP","ALT","AST",
                      "BIL","CHE","CHOL","CREA","GGT","PROT")

# 1 and 2 for blood donor and suspect blood donor, 2,3,4 for hepatitis, fibrosis,cirrhosis respectively
HCVdata$Category <- factor(HCVdata$Category,labels=c(1,2,3,4,5),
                           levels=c('0=Blood Donor',
                                    '0s=suspect Blood Donor',
                                    '1=Hepatitis',
                                    '2=Fibrosis', 
                                    '3=Cirrhosis'))


# 0 for male, 1 for female
HCVdata$Sex <- factor(HCVdata$Sex,levels=c("m","f"),labels=c("0","1"))
HCVdata=na.omit(HCVdata[c("Category","Age","Sex","ALB","ALP","ALT","AST",
                          "BIL","CHE","CHOL","CREA","GGT","PROT")])
for(var in 1:13)
{
  HCVdata[,var]=as.numeric(HCVdata[,var])
}

tail(HCVdata)
```

# EDA!!!

```{r}
#class information, distribution of "category"
library(dplyr)
HCVdata %>% 
  group_by(Category) %>%
  summarise(no_rows = length(Category))
#mean of each variable
colMeans(HCVdata)
#median of each variable
apply(HCVdata,2,median)
```


## train and test split 7:3
```{r}
## train and test set 7:3
HCVdata<-HCVdata[complete.cases(HCVdata),]
set.seed(4850)
sample <- sample.int(n = nrow(HCVdata), size = floor(.70*nrow(HCVdata)), replace = F)
train <- HCVdata[sample, ]
test <- HCVdata[-sample, ]

```

## roc with random forest

```{r}
#binary category
#1 for HCV, 0 for donor(regular/suspect)
set.seed(4850)
train$binary <- ifelse(as.numeric(train$Category)>2,1,0)
test$binary <- ifelse(as.numeric(test$Category)>2,1,0)
#barplot on binary
counts <- table(train$binary)
barplot(counts, main="HCV distribution",
   xlab="Binary")
#load libraries
library(randomForest)
rfmod <- randomForest(formula = binary ~ .-Category, data = train, ntree = 10, maxnodes= 100, norm.votes = F) 
suppressMessages(library(dplyr))
testm <- mutate(test,
                rf_pred = predict(rfmod,newdata = test,
                                   type="response"))

suppressMessages(library(pROC))

rocrf <- roc(testm$binary,testm$rf_pred)
AUCrf <- auc(rocrf)
rs <- rocrf[['rocs']]


```

## Mixed model GLMM

### binary random: AST

```{r}
suppressMessages(library(ggpubr))
library(ggplot2)
agePlot=ggplot(train, aes(x=Age,y=binary))+geom_point()
ALPPlot=ggplot(train, aes(x=ALP,y=binary))+geom_point()
ALBPlot=ggplot(train, aes(x=ALB,y=binary))+geom_point()

# regular logistic model
bmod <- glm(binary ~.-Category,binomial,data=,train)

#GLMM model random effect:Age
library(MASS)
set.seed(4850)
suppressMessages(modpql1 <- glmmPQL(binary ~Sex+ALB+Age+ALT+ALT+BIL+CHE+CHOL+CREA+GGT+PROT,
                  data=train, random= ~ 1|AST, family=binomial))
suppressMessages(drop1(modpql1, test="Chi"))

testm1 <- mutate(test,
                glmm_pred = predict(modpql1,newdata = test,
                                   type="response"))

suppressMessages(library(pROC))

roc1 <- roc(testm1$binary,testm1$glmm_pred)
AUC <- auc(roc1)
rs <- roc1[['rocs']]
coords(roc1,"best",ret=c("threshold",
"specificity", "sensitivity", "accuracy","precision"))
```

# Random effect:CHE
```{r}
#GLMM model random effect:CHE
library(MASS)
set.seed(4850)
suppressMessages(modpql2 <- glmmPQL(binary ~Sex+ALB+Age+ALT+ALT+BIL+AST+CHOL+CREA+GGT+PROT,
                  data=train, random= ~ 1|CHE, family=binomial))
suppressMessages(drop1(modpql2, test="Chi"))

testm2 <- mutate(test,
                glmm_pred = predict(modpql2,newdata = test,
                                   type="response"))

suppressMessages(library(pROC))

roc2 <- roc(testm2$binary,testm2$glmm_pred)
coords(roc2,"best",ret=c("threshold",
"specificity", "sensitivity", "accuracy","precision"))
```

# Random effect:Sex
```{r}
#GLMM model random effect:Sex
library(MASS)
set.seed(4850)
suppressMessages(modpql3 <- glmmPQL(binary ~CHE+ALB+Age+ALT+ALT+BIL+AST+CHOL+CREA+GGT+PROT,
                  data=train, random= ~ 1|Sex, family=binomial))
suppressMessages(drop1(modpql3, test="Chi"))

testm3 <- mutate(test,
                glmm_pred = predict(modpql3,newdata = test,
                                   type="response"))

suppressMessages(library(pROC))

roc3 <- roc(testm3$binary,testm3$glmm_pred)
coords(roc3,"best",ret=c("threshold",
"specificity", "sensitivity", "accuracy","precision"))
```



## Deep learning

### binary

```{r}
library(dplyr)
library(keras)
library(tensorflow)
library(tfdatasets)



set.seed(4850)
# Store the overall correlation in `M`
M <- cor(train[,1:10])

# Plot the correlation plot with `M`
library(corrplot)
predictorsCorr=corrplot(M, method="circle")

figure <- ggarrange(agePlot, ALPPlot, ALBPlot,predictorsCorr,
                    labels = c("A", "B", "C","D"),
                    ncol = 2, nrow = 2)
figure
#normalize 
spec <- feature_spec(train, binary ~ .-Category ) %>% 
  step_numeric_column(all_numeric(), normalizer_fn = scaler_standard()) %>% 
  fit()
spec

layer <- layer_dense_features(
  feature_columns = dense_features(spec), 
  dtype = tf$float32
)
suppressMessages(layer(train))

input <- layer_input_from_dataset(train[,2:13])


output <- input %>% 
  layer_dense_features(dense_features(spec)) %>% 
  layer_dense(units = 64, activation = "relu") %>%
  layer_dense(units = 64, activation = "relu") %>%
  layer_dense(units = 1) 

dpmod <- keras_model(input, output)





dpmod %>% 
  compile(
    loss = "mse",
    optimizer = optimizer_rmsprop(),
    metrics = list("mean_absolute_error")
  )

build_model <- function() {
  input <- layer_input_from_dataset(train[,2:13])
  
  output <- input %>% 
    layer_dense_features(dense_features(spec)) %>% 
    layer_dense(units = 64, activation = "relu") %>%
    layer_dense(units = 64, activation = "relu") %>%
    layer_dense(units = 1) 
  
  dpmod <- keras_model(input, output)
  
  dpmod %>% 
    compile(
      loss = "mse",
      optimizer = optimizer_rmsprop(),
      metrics = list("mean_absolute_error")
    )
  
  dpmod
}


# Display training progress by printing a single dot for each completed epoch.
print_dot_callback <- callback_lambda(
  on_epoch_end = function(epoch, logs) {
    if (epoch %% 80 == 0) cat("\n")
    cat(".")
  }
)    

dpmod <- build_model()

history <- dpmod %>% fit(
  x = train[2:13],
  y = train$binary,
  epochs = 500,
  validation_split = 0.2,
  verbose = 0,
  callbacks = list(print_dot_callback)
)


library(ggplot2)

plot(history)



# it will stop when no more improvement
early_stop <- callback_early_stopping(monitor = "val_loss", patience = 20)

dpmod <- build_model()

history <- dpmod %>% fit(
  x = train[2:13],
  y = train$binary,
  epochs = 500,
  validation_split = 0.2,
  verbose = 0,
  callbacks = list(early_stop)
)

plot(history)

suppressMessages(library(dplyr))
testm <- mutate(test,
                dp_pred = dpmod %>% predict(test[,2:13]), type="response")



rocnn <- roc(testm$binary,testm$dp_pred)
AUCnn <- auc(rocnn)
rs <- rocnn[['rocs']]
suppressMessages(summary(dpmod))
```


```{r}
#RM,(AST ALT ALP) glmm, nn
coords(rocrf,"best",ret=c("threshold",
"specificity", "sensitivity", "accuracy","precision"))##the random forest model

coords(roc1,"best",ret=c("threshold",
"specificity", "sensitivity", "accuracy","precision"))# the AST GLMM model
coords(roc2,"best",ret=c("threshold",
"specificity", "sensitivity", "accuracy","precision"))#the CHE GLMM model
coords(roc3,"best",ret=c("threshold",
"specificity", "sensitivity", "accuracy","precision"))# the Sex GLMM model
coords(rocnn,"best",ret=c("threshold",
"specificity", "sensitivity", "accuracy","precision"))# the nn GLMM model

#importance: impurity gini importance
c(log(importance(rfmod)),importance(rfmod))
#neural network and random forest
plot(rocrf)
plot(rocnn, add=TRUE, col='blue')
legend(1.45, 0.5, legend=c("RF", "NN"),
       col=c( "black","blue"), lty=1, cex=0.8)


#three glmm roc curve
plot(roc1)
plot(roc2, add=TRUE, col='red')
plot(roc3, add=TRUE, col='blue')
legend(1.45, 0.5, legend=c("AST", "CHE", "Sex"),
       col=c( "black","red", "blue"), lty=1, cex=0.8)
#randomforest best glmm and nn roc curve
plot(rocrf)
plot(roc3, add=TRUE, col='red')
plot(rocnn, add=TRUE, col='blue')
legend(1.45, 0.5, legend=c("RF", "Sex-GLMM", "NN"),
       col=c( "black","red", "blue"), lty=1, cex=0.8)
```



































